#!/bin/bash

P=${1}

echo "Changing wallpaper to ${P}"

# wal -n -i ${P}
# sleep 0.2
swww img ${P} --transition-type wipe --transition-step 100 --transition-fps 60 &

# killall waybar
# pkill waybar
# sleep 0.2

# waybar &